version: '2.1'
services:
  database:
    container_name: dhis2-database
    image: mdillon/postgis:9.5
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis
      POSTGRES_PASSWORD: dhis
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - dhis2_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432 -d dhis"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    container_name: dhis2-web
    image: dhis2/dhis2-web:2.40-tomcat7-jre8-latest
    environment:
      JAVA_OPTS: "-Xms1024m -Xmx4000m"
      POSTGRES_DB: dhis
    ports:
      - "8085:8080"
    depends_on:
      database:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c", "./wait-for-it.sh -t 0 database:5432 -- catalina.sh run"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
